pre-commit: handle deleted files

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,10 +9,12 @@ echo "Starting prospector analysis using configuration from .prospector.yml..."
 # prospector 1>/dev/null
 
 for file in $( git diff --name-only --cached ); do 
-    prospector ${file} 1>/dev/null
-    if [ $? != "0" ]; then
-        echo "Commit aborted. Run 'prospector ${file}' to see the errors."
-        exit 1
+    if [ -f ${file} ]; then # deal with files that are deleted
+        prospector ${file} 1>/dev/null
+        if [ $? != "0" ]; then
+            echo "Commit aborted. Run 'prospector ${file}' to see the errors."
+            exit 1
+        fi
     fi
 done 
 
